version: "3.7"
services:
  pg:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - notes_data:/var/lib/postgresql/data/pgdata/
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: note
      PGDATA: /var/lib/postgresql/data/pgdata
volumes:
  notes_data:
