version: "3.3"
services:
  ms:
    image: mysql:latest
    container_name: some-mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: note
    deploy:
      resources:
        limits:
          memory: 30M
    restart: always
  web-mysql:
    depends_on:
      - ms
    container_name: fine-notes
    build: .
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 100M
    restart: always
volumes:
  mysql_data:
