version: "3.3"
services:
  pg:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - notes_data:/var/lib/postgresql/data/pgdata/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: note
      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          memory: 30M
    restart: always
  web:
    depends_on:
      - pg
    container_name: fine-note
    build: .
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 100M
    restart: always
volumes:
  notes_data:
