server:
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-50-17-90-177.compute-1.amazonaws.com:5432/dsaqtg42g441a
    username: dyplyozvzyiplf
    password: 4a6b048c46e9a65506974ec66cc0706619cc4691a8e0156d9b3f04eaf5d1b349

  #    url: jdbc:postgresql://pg:5432/note
  #    username: postgres
  #    password: postgres
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/test
  #    username: root
  #    password: password
  #  security:
  #    user:
  #      name: user
  #      password: user
  jpa:
    generate-ddl: true
    show-sql: true
vaadin:
  async-supported: true