server:
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_MYSQL_URL}/note
    username: ${DATASOURCE_MYSQL_USERNAME}
    password: ${DATASOURCE_MYSQL_PASSWORD}

  #  security:
  #    user:
  #      name: user
  #      password: user
  jpa:
    generate-ddl: true
    show-sql: true
vaadin:
  async-supported: true