server:
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_POSTGRES_URL}/note
    username: ${DATASOURCE_POSTGRES_USERNAME}
    password: ${DATASOURCE_POSTGRES_PASSWORD}
  #  security:
  #    user:
  #      name: user
  #      password: user
  jpa:
    generate-ddl: true
    show-sql: true
vaadin:
  async-supported: true