server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-247-169-129.eu-west-1.compute.amazonaws.com:5432/db17f6nuog9olu
    username: zbqmjqhkqayjuc
    password: 1f8e74ac40260ca0a48664791f7552d03763a0396b9f34d32f783959fef8a764

  #    url: jdbc:postgresql://pg:5432/note
  #    username: postgres
  #    password: postgres
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/test
  #    username: root
  #    password: password
  #  security:
  #    user:
  #      name: user
  #      password: user
  jpa:
    generate-ddl: true
    show-sql: true